import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    sectionContainer: {
        flex: 0.15,
        backgroundColor: 'white',
        marginTop: 12,
        marginHorizontal: 18,
        marginBottom: 48,
        flexDirection: 'column',
        justifyContent: 'space-between',
        paddingBottom: 12,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#9b9b9bff',
        marginBottom: 12,
    },
    dateNameContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    calendarContainer: {
        width: '36%',
        height: 36,
        borderWidth: 1,
        borderColor: 'gray',
        borderRadius: 6,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 6,
    },
    calendarButtonTxt: {
        fontSize: 14,
        color: 'gray',
    },
    eventDescriptionInputContainer: {
        width: '60%',
        borderWidth: 1,
        borderColor: 'gray',
        borderRadius: 6,
        height: 36,
    },
    eventDescriptionInput: {
        fontSize: 14,
        color: 'gray',
        paddingHorizontal: 6,
        paddingVertical: 6,
    },
    categoryButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    dropdownButtonStyle: {
        width: '60%',
        // width: 90,
        height: 36,
        borderWidth: 1,
        borderColor: 'gray',
        borderRadius: 6,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 6,
    },
    dropdownButtonTxtStyle: {
        flex: 1,
        fontSize: 14,
        color: 'black',
    },
    dropdownItemStyle: {
        width: '100%',
        flexDirection: 'row',
        paddingHorizontal: 12,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 8,
    },
    dropdownItemTxtStyle: {
        flex: 1,
        fontSize: 12,
        color: '#151E26',
    },
    addEventButton: {
        width: '36%',
        height: 36,
        borderWidth: 1,
        backgroundColor: '#363636ff',
        borderRadius: 6,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 6,
        elevation: 3,
    },
    addEventButtonTxt: {
        fontSize: 14,
        color: 'white',
        fontWeight: 'bold',
        justifyContent: 'center',
    },
});

export default styles;